@Restaurant.API_HostAddress = https://localhost:7163
@id = 1
GET {{Restaurant.API_HostAddress}}/api/restaurants

###
  
GET {{Restaurant.API_HostAddress}}/api/restaurants/GetRestaurant/{{id}}

###

GET {{Restaurant.API_HostAddress}}/api/restaurants/GetRestaurant/{{id}}

###

GET {{Restaurant.API_HostAddress}}/api/restaurants/GetRestaurant/{{id}}

###

GET {{Restaurant.API_HostAddress}}/api/restaurants/get-all-restaurants

###

GET {{Restaurant.API_HostAddress}}/api/restaurants/GetRestaurant/{{id}}

###

POST {{Restaurant.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email":"User@test.com",
  "password":"P@ssword1"
}

Post{{Restaurant.API_HostAddress}}/api/Identity/register

###
